/* This function is used for providing quotes once the "More Quotes, Please" button from the index is clicked. One array (quotes) holds all the quotes, while the other (usedQuotes) is the container for used quotes. Once a quote has been displayed, it will move into the usedQuotes array, until all quotes have been used. Once all quotes have been used and moved to the usedQuotes array, the IF statement activates, and copies all the quotes from the usedQuotes array to the quotes array, and then makes the usedQuotes array empty again. The quotes are displayed randomly from the quotes array. There is a chance (that decreases with each new addition to the quotes array) that a quote can be displayed twice */

(function() {

	var quotes = [

		'I don\'t have the solution...But I certainly do admire the problem<br/><b>Ashleigh Brilliant</b>',
		'A day without sunshine is like, you know, night<br/><b>Steve Martin</b>',
		'People who think they know everything are a great annoyance to those of us who do<br/><b>Isaac Asimov</b>',
		'Get your facts first, then you can distort them as you please<br/><b>Mark Twain</b>',
		'I\'m sorry, if you were right, I\'d agree with you<br/><b>Robin Williams</b>',
		'There\'s a very fine line between not listening and not caring. I like to think I walk that line every day of my life<br/><b>Church from \"Red vs Blue\"</b>',
		'Procrastination is the art of keeping up with yesterday<br/><b>Don Marquis</b>',
		'I love deadlines. I like the whooshing sound they make as they fly by<br/><b>Douglas Adams</b>',
		'Weather forecast for tonight: Dark. Continued dark overnight, with widely scattered light by morning<br/><b>George Carlin</b>',
		'Isn\'t a bit unnerving that doctors call what they do \"Practice\"?<br/><b>George Carlin</b>',
		'If two wrongs don\'t make a right, try three<br/><b>Laurence J. Peter</b>',
		'My life needs more editing<br/><b>Mort Sahl</b>',
		'Not only do I not know what\'s going on, I wouldn\'t know what to do about it if I did<br/><b>George Carlin</b>',
		'The reason I talk to myself is that I\'m the only one whose answers I accept<br/><b>George Carlin</b>',
		'Spring is nature\'s way of saying, \"Let\'s Party!\"<br/><b>Robin Williams</b>',
		'It is a scientific fact that your body will not absorb cholesterol if you take it from another person\'s plate<br/><b>Dave Barry</b>',
		'I am so clever that sometimes I don\'t understand a single word of what I am saying<br/><b>Oscar Wilde</b>',
		'I never forget a face, but in your case I\'ll make an exception<br/><b>Groucho Marx</b>',
		'Before you judge a man, walk a mile in his shoes. After that, who cares? He\'s a mile away and you\'ve got his shoes!<br/><b>Billy Connolly</b>',
		'The difference between genius and stupidity is that genius has its limits<br/><b>Albert Einstein</b>',
		'If you find it hard to laugh at yourself, I would be happy to do it for you<br/><b>Groucho Marx</b>',
		'To steal ideas from one person is plagiarism; to seal from many is research<br/><b>Steven Wright</b>',
		'The road to success is dotted with many tempting parking spaces<br/><b>Will Rogers</b>',
		'Life is hard; it\'s harder if you\'re stupid<br/><b>John Wayne</b>',
		'A lie gets halfway around the world before the truth has a chance to get its pants on<br/><b>Winston Churchill</b>',
		'If you think nobody cares if you\'re alive, try missing a couple of car payments<br/><b>Earl Wilson</b>',
		'If you try to fail, and succeed, which have you done?<br/><b>George Carlin</b>',
		'A lot of people are afraid of heights. Not me, I\'m afraid of widths<br/><b>Steven Wright</b>',
		'By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day<br/><b>Robert Frost</b>',
		'I\'d rather have 1% of the effort of 100 men than 100% of my own effort<br/><b>J. Paul Getty</b>',
		'Recession is when a neighbor loses his job. Depression is when you lose yours<br/><b>Ronald Reagan</b>',
		'It\'s true that had work never killed anybody. But I figure, why take the chance?<br/><b>Ronald Reagan</b>',
		'I have not failed. I\'ve just found 10,000 ways that won\'t work<br/><b>Thomas A. Edison</b>',
		'I can resist everything except temptation<br/><b>Oscar Wilde</b>',
		'It\'s always darkest before the dawn. So if you\'re going to steal your neighbor\'s newspaper, that\'s the time to do it<br/><b>Navjot Singh Sidhu</b>',
		'Always borrow money from a pessimist. He won\'t expect it back<br/><b>Oscar Wilde</b>',
		'May the forces of evil become confused on the way to your house<br/><b>George Carlin</b>',
		'It does not matter whether you win or lose, what matters is whether I win or lose!<br/><b>Steven Weinberg</b>',
		'Lead me not into temptation; I can find the way myself<br/><b>Rita Mae Brown</b>',
		'I have learned from my mistakes, and I am sure I can repeat them exactly<br/><b>Peter Cook</b>',
		'If you must make a noise, make it quietly<br/><b>Oliver Hardy</b>',
		'I always arrive late at the office, but I make up for it by leaving early<br/><b>Charles Lamb</b>',
		'The road to success is always under construction<br/><b>Lily Tomlin</b>',
		'What the world needs is more geniuses with humility; there are so few of us left<br/><b>Oscar Levant</b>',
		'It\'s always funny until someone gets hurt. Then it\'s just hilarious<br/><b>Bill Hicks</b>',
		'Talking about music is like dancing about architecture<br/><b>Steve Martin</b>',
		'Kilometers are shorter than miles. Save gas, take your next trip in kilometers<br/><b>George Carlin</b>',
		'I like coffee because it gives me the illusion that I might be awake<br/><b>Lewis Black</b>',
		'\"Be yourself\" is about the worst advice you can give to some people<br/><b>Thomas Lansing Masson</b>',
		'There is hardship in everything except eating pancakes<br/><b>Charles Spurgeon</b>',
		'It\'s simple: if it jiggles, it\'s fat<br/><b>Arnold Schwarzenegger</b>',
		'When in doubt, blow something up<br/><b>J. Michael Straczynski</b>',
		'There is no such thing as fun for the whole family<br/><b>Jerry Seinfeld</b>',
		'You know the trouble with real life? There\'s no danger music<br/><b>Jim Carrey</b>',
		'There\'s no better feeling in the world than a warm pizza box on your lap<br/><b>Kevin James</b>',
		'Don\'t sweat the petty things and don\'t pet the sweaty things<br/><b>George Carlin</b>',
		'My psychiatrist told me I was crazy and I said I want a second opinion. He said "Okay, you\'re ugly too"<br/><b>Rodney Dangerfield</b>',
		'I believe that if life gives you lemons, you should make lemonade...And try to find somebody whose life has given them vodka, and have a party<br/><b>Ron White</b>',
		'The man who smiles when things go wrong has thought of someone to blame it on<br/><b>Robert Block</b>',
		'Better to remain silent and be thought a fool than to speak out and remove all doubt<br/><b>Abraham Lincoln</b>',
		'Two wrongs do not make right; But three rights make a left<br/><b>George Lopez</b>',
		'I don\'t trust children. They\'re here to replace us<br/><b>Stephen Colbert</b>',
		'Why is there so much month left at the end of the money?<br/><b>John Barrymore</b>',
		'If there are no stupid questions, then what kind of questions do stupid people ask? Do they get smart just in time to ask questions?<br/><b>Scott Adams</b>',
		'Looking at cleavage is like looking at the sun. You don\'t stare at it. It\'s too risky. Ya get a sense of it and then you look away<br/><b>Jerry from \"Seinfeld\"</b>',
		'Hardware: the parts of a computer that can be kicked<br/><b>Jeff Pesis</b>',
		'There are two ways to write error-free programs; only the third one works<br/><b>Alan Perlis</b>',
		'I reject your reality and substitute my own<br/><b>Adam Savage</b>',
		'Computer Science is no more about computers than Astronomy is about telescopes<br/><b>Edsger W. Dijkstra</b>',
		'You know it\'s love when you memorize her IP number to skip DNS overhead<br/><b>Unknown</b>',
		'Everyone needs computer programming. It will be the way we speak to the servants<br/><b>John McCarthy</b>',
		'Of course I don\'t look busy, I did it right the first time<br/><b>Scott Adams</b>',
		'A clear conscience is usually the sign of a bad memory<br/><b>Steven Wright</b>',
		'Rice is great if you\'re really hungry and want to eat two thousand of something<br/><b>Mitch Hedberg</b>',
		'I\'m sick of following my dreams. I\'m just going to ask them where they\'re goin\', and hook up with them later<br/><b>Mitch Hedberg</b>',
		'If at first you don\'t succeed, try, try again. Then quit. There\'s no point in being a damn fool about it<br/><b>W. C. Fields</b>',
		'There are 10 types of people in the world: those who understand binary, and those who don\'t<br/><b>Unknown</b>',
		'Never half-ass two things. Whole-ass one thing<br/><b>Ron Swanson from \"Parks and Recreation\"</b>',
		'Change is inevitable, except from a vending machine<br/><b>Unknown</b>',
		'No one can be exactly like me. Sometimes even I have trouble doing it<br/><b>Tallulah Bankhead</b>',
		'Do you know what \'meteorologist\' means in English? It means liar<br/><b>Lewis Black</b>',
		'When life gives you lemons, squirt someone in the eye<br/><b>Cathy Guisewite</b>',
		'Never miss a good chance to shut up<br/><b>Will Rogers</b>',
		'One should never give up on hope...Unless that\'s the name of the girl who cheated on you, in which case, yeah, give her up<br/><b>Carroll Bryant</b>',
		'I understood it-until you tried to explain it<br/><b>Erin Pracht</b>',
		'I refuse to answer that question on the grounds that I don\'t know the answer<br/><b>Douglas Adams</b>',
		'Nothing travels faster than the speed of light, with the possible exception of bad news, which obeys its own special laws<br/><b>Douglas Adams</b>',
		'I know all those words, but that sentence makes no sense to me<br/><b>Matt Groening</b>',
		'Who was the guy who first looked at a cow and said \"I think I\'ll drink whatever comes out of these when I squeeze \'em\"?<br/><b>Bill Watterson</b>',
		'Never knock on death\'s door. Ring the doorbell then run. He totally hates that<br/><b>Darynda Jones</b>',
		'If I\'m walking on thin ice, I might as well dance my way across<br/><b>Mercedes Lackey</b>',
		'Oh, you hate your job? Why didn\'t you say so? There\'s a support group for that. It\'s called EVERYBODY, and they meet at the bar<br/><b>Drew Carey</b>',
		'Anybody who says they are a good liar obviously is not, because any legitimately savvy liar would always insist they\'re honest about everything<br/><b>Chuck Klosterman</b>',
		'If at first you don\'t succeed, destroy all evidence that you tried<br/><b>Steven Wright</b>',
		'I\'m not dumb. I just have a command of thoroughly useless information<br/><b>Bill Watterson</b>',
		'I think I am, therefore, I am...I think<br/><b>George Carlin</b>',
		'I believe in equality. Equality for everybody. No matter how stupid they are or how superior I am to them<br/><b>Steve Martin</b>',
		'When I get sad, I stop being sad and be awesome instead<br/><b>Barney Stinson from \"How I Met Your Mother\"</b>',
		'You are only young once, but you can stay immature indefinitely<br/><b>Ogden Nash</b>',
		'To alcohol! The cause of, and solution to, all of life\'s problems<br/><b>Homer Simpson from \"The Simpsons\"</b>',
		'The length of a film should be directly related to the endurance of the human bladder<br/><b>Alfred Hitchcock</b>',
		'Never put off till tomorrow what may be done day after tomorrow just as well<br/><b>Mark Twain</b>',
		'College is the best time of your life. When else are your parents going to spend several thousand dollars a year just for you to go to a strange town to get drunk every night?<br/><b>David Wood</b>',
		'Be twice as funny as you are outrageous, because no one can resist the truth wrapped in a good joke<br/><b>Milo Yiannopoulos</b>',
		'Aim for the sun. That way if you miss, at least your arrow will fall far away, and the person it kills will likely be someone you don\'t know<br/><b>Brandon Sanderson</b>',
		'Time line? Time isn\'t made out of lines. It is made out of circles. That is why clocks are round<br/><b>Caboose from \"Red vs Blue\"</b>',
		'We\'re not retreating! We\'re advancing toward future victories<br/><b>Sarge from \"Red vs Blue\"</b>',
		'Just act like you normally do. Wait, not like you, act like someone more brave...and smarter...and more masculine for God\'s sake!<br/><b>Sarge from \"Red vs Blue\"</b>',
		'There are two kinds of people in the world; those who have a plan prepared for when the zombies take over the Earth, and those who don\'t. We call those last people \"Dinner\"<br/><b>Grif from \"Red vs Blue\"</b>',
		'People learn English all the time...it aren\'t that hard<br/><b>Tucker from \"Red vs Blue\"</b>',
		'No matter how bad things seem, they can\'t be any better, and they can\'t be any worse, because that\'s the way things are, and you better get used to it, Nancy. Quit your bitchin\'<br/><b>Church from \"Red vs Blue\"</b>',
		'Ahh, the middle finger. The most communicative of fingers<br/><b>Guybrush Threepwood from the \"Monkey Island\" series</b>',
		'If fucking is power, I should be the Hulk by now<br/><b>Richard Kadrey</b>',
		'Two wrongs don\'t make a right, but they make a good excuse<br/><b>Thomas Szasz</b>',
		'I like work: it fascinates me. I can sit and look at it for hours<br/><b>Jerome K. Jerome</b>',
		'The amount of sleep required by the average person is about five minutes more<br/><b>Max Kauffmann</b>',
		'There are two ways to handle a woman, and nobody knows either of them<br/><b>Frank McKinney Hubbard</b>',
		'Weddings are basically funerals with cake<br/><b>Rick Sanchez from \"Rick and Morty\"</b>',
		'A know-it-all is a person who knows everything except for how annoying he is<br/><b>Demetri Martin</b>',
		'Some things are exactly as they seem, folks. Killer Whales kill, Pilot Whales wear dark sunglasses. I\'m not sure how the Sperm Whale got his name, but I\'m not getting in the pool<br/><b>Ron White</b>',
		'When my time comes, I wanna be buried facedown. That way whoever doesn\'t like me can kiss my ass<br/><b>Red Foreman from \"That 70\'s Show\"</b>',
		'Society teaches us that having feelings and crying is bad and wrong. Well, that\'s baloney, because grief isn\'t wrong. There\'s such a thing as good grief. Just ask Charlie Brown<br/><b>Michael Scott from \"The Office\"</b>',
		'Sometimes I feel like everyone I work with is an idiot. And by sometimes, I mean all times. All the time. Every of the time<br/><b>Kevin Malone from \"The Office\"</b>',
		'I never lie. I believe everything I say, so it\'s not a lie<br/><b>Mark Wahlberg</b>',
		'The message \"Bad command or file name\" is as informative as \"If you don\'t know why I\'m mad at you, then I\'m certainly not going to tell you<br/><b>Unknown</b>',
		'\"Meow\" means \"woof\" in cat<br/><b>George Carlin</b>',
		'I went to a bookstore and asked the saleswoman, "Where\'s the self-help section?\" She said if she told me, it would defeat the purpose<br/><b>George Carlin</b>',
		'[There\'s no \"I\" in team, Grif] Oh, yeah? Well, there\'s no \"U\", either. So I guess if \"I\'m\" not on the team and \"you\'re\" not on the team, nobody\'s on the goddamned team! The team sucks!<br/><b>Grif from \"Red vs Blue\"</b>',
		'Some people have no idea what they\'re doing, and a lot of them are really good at it<br/><b>George Carlin</b>',
		'When you\'re not looking, somebody\'ll sneak up and write \"Fuck you\" right under your nose<br/><b>J.D. Salinger</b>',
		'As far as I\'m concerned, if something is so complicated that you can\'t explain it in 10 seconds, then it\'s probably not worth knowing anyway<br/><b>Bill Watterson</b>',
		'One morning I shot an elephant in my pajamas. How he got in my pajamas I\'ll never know<br/><b>Groucho Marx</b>',
		'When all else fails, there\'s always delusion<br/><b>Conan O\'Brien</b>',
		'It\'s not denial. I\'m just selective about the reality I accept<br/><b>Bill Watterson</b>',
		'When I was growing up I always wanted to be someone. Now I realize I should have been more specific<br/><b>Lily Tomlin</b>',
		'The biggest challenge after success is shutting up about it<br/><b>Criss Jami</b>',
		'I like nonsense, it wakes up the brain cells<br/><b>Dr. Seuss</b>',
		'I never made a mistake in my life; at least, never one that I couldn\'t explain away afterwards<br/><b>Rudyard Kipling</b>',
		'A good night sleep, or a ten minute bawl, or a pint of chocolate ice cream, or all three together, is good medicine<br/><b>Ray Bradbury</b>',
		'You can only be in a bad mood for so long before you have to face up to the fact that it isn\'t a bad mood at all; it\'s just your sucky personality<br/><b>Megan McCafferty</b>',
		'You have to remember one thing about the will of the people: it wasn\'t that long ago that we were swept away by the Macarena<br/><b>Jon Stewart</b>',
		'I find my life is a lot easier the lower I keep my expectations<br/><b>Bill Watterson</b>',
		'Telling an introvert to go to a party is like telling a saint to go to Hell<br/><b>Criss Jami</b>',
		'An original idea. That can\'t be too hard. The library must be full of them<br/><b>Stephen Fry</b>',
		'Just give me a second. Attempting to give a fuck...Attempting harder to give a fuck...Sorry, there was an error; fuck not given<br/><b>Suzanne Wright</b>',
		'We\'re not retreating. We\'re advancing in reverse<br/><b>Skulduggery Pleasant from \"Skulduggery Pleaseant\" series</b>',
		'We must have pie. Stress cannot exist in the presence of a pie<br/><b>David Mamet</b>',
		'If you had to identify, in one word, the reason why the human race has not achieved, and never will achieve, its full potential, that word would be \"meetings\"<br/><b>Dave Barry</b>',
		'I\'ve been accused of vulgarity. I say that\'s bullshit<br/><b>Mel Brooks</b>',
		'You know on TV when there\'s one of those awkward, shocking moments and all you hear are the crickets in the background? Well chirp fucking chirp...this is one of those moments<br/><b>Emma Chase</b>',
		'When in doubt, look intelligent<br/><b>Garrison Keillor</b>',
		'Learn from yesterday, live for today, look to tomorrow, rest this afternoon<br/><b>Charles M. Schulz</b>',
		'Thinking is hard work, which is why you don\'t see many people doing it<br/><b>Sue Grafton</b>',
		'My opinions may have changed, but not the fact that I\'m right<br/><b>Ashleigh Brilliant</b>',
		'Honesty may be the best policy, but it\'s important to remember that apparently, by elimination, dishonesty is the second-best policy<br/><b>George Carlin</b>',
		'I\'m realizing that some of my greatest (or at least most determined) genius lies in my ability to procrastinate<br/><b>Scott Stabile</b>',
		'\"If you want to shoot the general, first shoot the horse\"<br/>\"If you wanna shoot the general, then you should just SHOOT THE GENERAL!\"<br/><b>Ling Yao and Edward Elric from \"Fullmetal Alchemist: Brotherhood\"</b>',
		'Every year, many, many stupid people graduate from college. And if they can do it, so can you<br/><b>John Green</b>',
		'The nice part about being a pessimist is that you are constantly being either proven right or pleasantly surprised<br/><b>George F. Will</b>',
		'Everybody\'s got to believe in something. I believe I\'ll have another beer<br/><b>W.C. Fields</b>',
		'There is a great need for a sarcasm font<br/><b>Darynda Jones</b>',
		'Whoever said the pen is mightier than the sword obviously never encountered automatic weapons<br/><b>Douglas MacArthur</b>',
		'Everything here is edible; even I\'m edible. But that, dear children, is cannibalism, and is in fact frowned upon in most societies<br/><b>Johnny Depp</b>',
		'I\'d kill for a Nobel Peace Prize<br/><b>Steven Wright</b>',
		'Just about everything in this world is easier said than done, with the exception of \"systematically assisting Sisyphus\'s stealth, cyst-susceptible,\" which is easier done than said<br/><b>Lemony Snicket</b>',
		'Only Irish coffee provides in a single glass all four essential food groups: alcohol, caffeine, sugar and fat<br/><b>Alex Levine</b>',
		'All are lunatics, but he who can analyze his delusion is called a philosopher<br/><b>Ambrose Bierce</b>',
		'ROFL! What? Are you really rolling on the floor laughing? Well, please stay down there for a sec while I KICK YOUR ASS<br/><b>David Levithan</b>',
		'My formula for life is very simple: in the morning, wake up; at night, go to sleep. In between I try and occupy myself as best I can<br/><b>Cary Grant</b>',
		'Don\'t mess with a wizard when he\'s wizarding!<br/><b>Jim Butcher</b>',
		'Talk is cheap. Show me the code<br/><b>Linus Torvalds</b>',
		'The two most beautiful words in the English language are \"cheque enclosed\"<br/><b>Dorothy Parker</b>',
		'If your kid needs a role model and you ain\'t it, you\'re both fucked<br/><b>George Carlin</b>',
		'Gravity is a contributing factor in nearly 73 percent of all accidents involving falling objects<br/><b>Dave Barry</b>',
		'Shin: a device for finding furniture in the dark<br/><b>Steven Wright</b>',
		'No man\'s life, liberty, or property are safe while the legislature is in session<br/><b>Gideo J. Tucker</b>',
		'Life is half delicious yogurt, half crap, and your job is to keep the plastic spoon in the yogurt<br/><b>Scott Adams</b>',
		'I\'m no cactus expert, but I know a prick when I see one<br/><b>Mark A. Cooper</b>',
		'There are too many idiots in this world. And having said it, I have the burden of proving it<br/><b>Frantz Fanon</b>',
		'If anger were mileage, I\'d be a very frequent flyer, right up there in First Class<br/><b>Gina Barreca</b>',
		'Computers are like Old Testament gods; lots of rules and no mercy<br/><b>Joseph Campbell</b>',
		'It doesn\'t matter what temperature a room is, it\'s always room temperature<br/><b>Steven Wright</b>',
		'Wikipedia is the first place I go when I\'m looking for knowledge...or when I want to create some<br/><b>Stephen Colbert</b>',
		'The ability to speak does not make you intelligent<br/><b>George Lucas</b>',
		'Above all, if what you\'ve done is stupid, but works, it ain\'t stupid<br/><b>Robert Fulghum</b>',
		'Revenge is sweet and not fattening<br/><b>Alfred Hitchcock</b>',
		'I\'d give my right arm to be ambidextrous<br/><b>Yogi Berra</b>',
		'I\'m not stubborn. My way is just better<br/><b>Maya Banks</b>',
		'Don\'t explain computers to laymen. Simpler to explain sex to a virgin<br/><b>Robert A. Heinlein</b>',
		'If it\'s zero degrees outside today and it\'s supposed to be twice as cold tomorrow, how cold is it going to be?<br/><b>Steven Wright</b>',
		'My powers of persuasion are only as strong as the bullshit I have to back it up<br/><b>Darynda Jones</b>',
		'Nobody messes around with a nerd\'s computer and escapes unscathed<br/><b>E.A. Bucchianeri</b>',
		'The worst time to have a heart attack is during a game of charades<br/><b>Demetri Martin</b>',
		'I don\'t have a girlfriend. But I do know a woman who\'d be mad at me for saying that<br/><b>Mitch Hedberg</b>',
		'I don\'t understand the whole concept of a massage. You get a woman to rub all over every single part of your body except the one part you really want rubbed on<br/><b>Rodney Carrington</b>',
		'Childhood is throwing rocks at shit you shouldn\'t be throwing rocks at<br/><b>Joel Heyman</b>',
		'If you make enough bad decisions, every once in a while things work out for you<br/><b>Geoff Ramsey</b>',
		'Do you think goosebumps for blind people is just like reading a bunch of jumbled letters?<br/><b>Gavin Free</b>',
		'I\'m really smart sometimes. But only sometimes<br/><b>Gavin Free</b>',
		'I don\'t do ups. Ups defy gravity. Gravity is a law. I obey the law<br/><b>John Pinette</b>',
		'To be sure of hitting the target, shoot first, and call whatever you hit the target<br/><b>Ashleigh Brilliant</b>',
		'When you go into court, you are putting your fate into the hands of twelve people who aren\'t smart enough to get out of jury duty<br/><b>Norm Crosby</b>',
		'My fake plants died because I did not pretend to water them<br/><b>Mitch Hedberg</b>',
		'Dachshund: A half-a-dog high and a dog-and-a-half long<br/><b>H.L. Mencken</b>',
		'If at first you don\'t succeed, failure may be your style<br/><b>Quentin Crisp</b>',
		'Accept who you are. Unless you\'re a serial killer<br/><b>Ellen DeGeneres</b>',
		'Polite conversation is rarely either<br/><b>Fran Lebowitz</b>',
		'Anything worth doing is worth doing slowly<br/><b>Mae West</b>',
		'I have a lot of beliefs and I live by none of them<br/><b>Louis C. K.</b>',
		'Haven\'t you noticed that every time the government fucks up, McDonald\'s has a new sandwich?<br/><b>Bill Burr</b>',
		'The next time you have a thought...let it go<br/><b>Ron White</b>',
		'There\'s a few things in life that are as satisfying as hitting a bird with a car<br/><b>Jeremy Dooley</b>',
		'If I remain perfectly still, it won\'t be able to see me<br/>*Eaten by a T-Rex*<br/>Mhmmmm. You know what, I think I blinked<br/><b>Michael Jones from \"Rage Quit\"</b>',
		'Yeah man, I tell ya what, man. That dang ol\' Internet, man. You just go on there and point and click. Talk about w-w-w-dot-w-com. An\'s lotsa nekkid chicks on there, man. Click. Click. Click. Click. Click. It\'s real easy, man<br/><b>Boomhauer from \"King of the Hill\"</b>',
		'If your sorority has to sell jam to buy beer, you\'re drinking too much<br/><b>Hank Hill from \"King of the Hill\"</b>',
		'Like I always say, there\'s no \"I\" in \"team\". There is a \"me,\" though, if you jumble it up<br/><b>Greggory House from \"House\"</b>',
		'Have you ever put a finger, algea-filled lake-water, or shampoo in there? Yeah, that gets your eyes screaming in pain pretty quick, doesn\'t? Unless you\'re using baby No More Tears shampoo, of course, in which case feel free to lather your eyeballs right on up, no worries<br/><b>Neil Pasricha</b>',
		'Ah, my birthday. Normally I\'d put on a festive hat and celebrate the fact that the Earth has circled the Sun one more time; I really didn\'t thing it was going to make it this year, but darn it if it wasn\'t the little planet that could all over again<br/><b>Greggory House from \"House\"</b>',
		'Do I get bonus points if I act like I care?<br/><b>Greggory House from \"House\"</b>',
		'There\'s a reason we don\'t let kids vote, or drink, or work in salt mines. They\'re idiots! Twenty year olds fall in and out of love more often than they change their oil filters. Which they should do more often<br/><b>Greggory House from \"House\"</b>',
		'Never in the history of calm down has anyone calmed down by being told to calm down<br/><b>Unknown</b>',
		'The power of friendship is bullshit<br/><b>Michael Jones</b>',
		'Roses are red, violets are blue, I have five fingers, the middle one is for you<br/><b>Gena Showalter</b>',
		'If it weren\'t for physics and law enforcement, I\'d be unstoppable<br/><b>Darynda Jones</b>',
		'Just relax and breathe through your ass<br/><b>Lewis Black</b>',
		'My common sense is tingling<br/><b>Deadpool</b>',
		'Paperwork wouldn\'t be so bad if it weren\'t for all the paper. And the work<br/><b>Darynda Jones</b>',
		'\"Sort of\" is such a harmless thing to say...sort of. It\'s just a filler. Sort of...it doesn\'t really mean anything. But after certain things, sort of means everything. Like...after \"I love you\"...or \"You\'re going to live\"...or \"It\'s a boy!\"<br/><b>Demetri Martin</b>',
		'I sometimes give myself excellent advice. Occasionally, I even listen to it<br/><b>Jim Butcher</b>',
		'The table of elements does not contain one of the most powerful elements that make up our world, and that is the element of surprise<br/><b>Lemony Snicket</b>',
		'I got my wife a mood ring. It works real good! When she\'s in a good mood it turns blue, but when shes\'s in a bad mood there\'s a red mark across my forehead<br/><b>Jeff Foxworthy</b>',
		'They say money talks, but all mine ever says is \"good-bye sucker\"<br/><b>Jill Shalvis</b>',
		'The \"Five Second Rule\" has many variations, including the \"Three Second Rule\", the \"Seven Second Rule\", and the extremely handy and versatile \"However Long It Takes Me to Pick Up This Food Rule\"<br/><b>Neil Pasricha</b>',
		'A good story should provoke discussion, debate, argument...and the occasional bar fight<br/><b>J. Michael Straczynski</b>',
		'So tell me, what\'s it like to live in a haze of constant stupidity?<br/><b>Hiei from \"Yu Yu Hakusho\"</b>',
		'I you removed all the arteries, veins, & capillaries from a person\'s body, and tied them end-to-end...the person will die<br/><b>Neil deGrasse Tyson</b>',
		'Time is a great teacher, but unfortunately it kills all its pupils<br/><b>Louis Hector Berlioz</b>',
		'Think of how stupid the average person is, and realize half of them are stupider than that<br/><b>George Carlin</b>',
		'Sometimes, when I\'m feeling down because nothing seems to be going right, I like to take a home pregnancy test. Then I can say, \"Hey, at least I\'m not pregnant\"<br/><b>Daniel Tosh</b>',
		'You know what a cubicle basically says? It basically says, like, \"You know what? We don\'t think you\'re smart enough for an office, but we don\'t want you to look at anybody\"<br/><b>Bill Burr</b>',
		'Whatever you do, always give 100%. Unless you\'re donating blood<br/><b>Bill Murray</b>',
		'Just beat my record for most consecutive days without dying<br/><b>Bill Murray</b>',
		'People have an annoying habit of remembering things they shouldn\'t<br/><b>Christopher Paolini</b>',
		'half of seeming clever is keeping you mouth shut at the right times<br/><b>Patrick Rothfuss</b>',
		'Employee of the month is a good example of how somebody can be both a winner and a loser at the same time<br/><b>Demetri Martin</b>',
		'If it doesn\'t work, at least it will be an interesting train wreck<br/><b>Craig Ferguson</b>',
		'I\'m not crazy, but I suspect the voices in my head are<br/><b>Kelli Sullivan</b>',
		'Sometimes you just gotta wear the tinfoil hat<br/><b>Gary Hopkins</b>',
		'The grass is always greener when it\'s covered money<br/><b>Craig Benzine</b>',
		'Even betting against myself, I could always find a way to lose<br/><b>Jonathan Tropper</b>',
		'Basically, I have two speeds...Hostile or smart-aleck. Your choice<br/><b>James Patterson</b>',
		'If a mute kid swears, should his mother wash his hands with soap?<br/><b>Steven Wright</b>',
		'Have you ever noticed that anybody driving slower than you is an idiot, and anyone going faster than you is a maniac<br/><b>George Carlin</b>',
		'I\'m not always a smartass. Sometimes I\'m just an ass',
		'Patience - A minor form of despair, disguised as a virtue<br/><b>Ambrose Bierce</b>',
		'Being human totally sucks most of the time. Video games are the only thing that make life bearable<br/><b>Ernest Cline</b>',
		'Could you put that in a memo and entitle it \"Shit I already know\"<br/><b>Sarge from \"Red vs Blue\"</b>',
		'All my life I\'ve had girls tell me, \"Not if you were the last man on Earth\". Well, that may be true, but let\'s see what happens when I\'m the last man on Earth with a sweet ass, pimped out ride, bitch!<br/><b>Tucker from \"Red vs Blue\"</b>',
		'Ah, nerd love. It is a beautiful thing, while also being an object of mockery and hilarity for those of us who are more sophisticated<br/><b>Cassandra Clare</b>',
		'Everywhere is within walking distance if you have the time<br/><b>Steven Wright</b>',
		'I intend to live forever. So far, so good<br/><b>Steven Wright</b>',
		'I\'ve been accused of vulgarity. I say that\'s bullshit<br/><b>Mel Brooks</b>',
		'To achieve great things, two things are needed: a plan and not quite enough time<br/><b>Leonard Bernstein</b>',
		'The face of a child can say it all, especially the mouth part<br/><b>Jack Handey</b>',
		'The less I know about other people\'s affairs, the happier I am. I\'m not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes<br/><b>Ron Swanson from \"Parks and Recreation\"</b>',
		'Behind every successful man is me, smiling and taking partial credit<br/><b>Tom Haverford from \"Parks and Recreation\"</b>',
		'Any dog under fifty pounds is a cat and cats are useless<br/><b>Ron Swanson from \"Parks and Recreation\"</b>',
		'There\'s only one thing I hate more than lying: skim milk. Which is water that\'s lying about being milk<br/><b>Ron Swanson</b>',
		'The three branches of government: military, corporate, and Hollywood<br/><b>Hyde from \"That 70\'s Show\"</b>',
		'That\'s a headline you never want to see. \"Captain Murderstab has been released on parole\"<br/><b>Brandon Farmahini from \"Achievement Hunter\"</b>',
		'Okay, the chickens are having some kind of festival dance around the baby. I thing they\'re gonna sacrifice it to the Chicken Lord<br/><b>Ryan Haywood from \"Achievement Hunter\"</b>',
		'The best part of winning is knowing that you all lost<br/><b>Ryan Haywood from \"Achievement Hunter\"</b>',
		'It\'s not a stereotype if it\'s always true<br/><b>Daniel Tosh</b>',
		'Truth hurts...maybe not as much as jumping on a bicycle with the seat missing...but it hurts<br/><b>Lt. Frank Drebin from \"The Naked Gun 2 1/2: The Smell of Fear\"</b>',
		'I don\'t hate you...I just don\'t like that you exist<br/><b>Gena Showalter</b>',
		'Ah coffee. The sweet balm by which we shall accomplish today\'s tasks<br/><b>Holly Black</b>',
		'If at first you don\'t succeed, then skydiving definitely isn\'t for you<br/><b>Steven Wright</b>',
		'There are two ways of arguing with a woman, and neither one works<br/><b>John Marston from \"Red Dead Redemption\"</b>',
		'Never be less interesting than your refrigerator magnets<br/><b>Demetri Martin</b>',
		'The best method for accelerating a computer is the one that boosts it by 9.8 m/s/s<br/><b>Unknown</b>',
		'The question of whether a computer can think is no more interesting than the question of whether a submarine can swim<br/><b>Edsger W. Dijkstra</b>',
		'Nerd life is just so much better than regular life<br/><b>John Green</b>',
		'Son, when a woman says nothing\'s wrong, it means everything\'s wrong; when a woman says everything\'s wrong, it means everything\'s wrong; and when a woman says that something isn\'t funny, you\'d better not laugh your ass off<br/><b>Homer Simpson from \"The Simpsons\"</b>',
		'According to the latest official figures, 43% of all statistics are totally worthless<br/><b>Ashleigh Brilliant</b>',
		'The problem with the designated driver program, it\'s not a desirable job, but if you ever get sucked into doing it, have fun with it. At the end of the night, drop them off at the wrong house<br/><b>Jeff Foxworthy</b>',
		'You know, somebody actually complimented me on my driving today. They left a little note on the windscreen, it said \"Parking Fine\"<br/><b>Tommy Cooper</b>',
		'It\'s strange, isn\'t it? You stand in the middle of a library and go \"aaaaaaaagghhhh\", and everyone just stares at you. But when you do the same thing on an airplane, and everyone joins in<br/><b>Tommy Cooper</b>',
		'Life would be a great deal easier if dead things had the decency to remain dead<br/><b>Doug MacLeod</b>',
		'Tolerance! The virtue that makes one bite his tongue so that he can tear out his hair<br/><b>Criss Jami</b>',
		'It\'s all fun and games until someone loses an eye. The it\'s fun and games can\'t see anymore<br/><b>James Hetfield</b>',
		'Life\'s too short not to sleep when you feel like it<br/><b>Neil Pasricha</b>',
		'It\'s especially hard to admit that you made a mistake to your parents, because, of course, you know so much more than they do<br/><b>Sean Covey</b>',
		'If you have the choice between humble and cocky, go with cocky. There\'s always time to be humble later, once you\'ve been prove horrendously, irrevocably wrong<br/><b>Kinky Friedman</b>',
		'It\'s spider season. Every year, right about now, thousands of the godless eight-legged bastards emerge from the bowels of hell (or the garden, whichever\'s nearest) with the sole intention of tormenting humankind<br/><b>Charlie Brooker</b>',
		'We are all a little weird. And we like to think that there is always someone weirder. I mean, I am sure some of you are looking at me and thinking, \"Well, at least I am not as weird as you,\" and I am thinking, \"Well, at least I am not as weird as the people in the loony bin," and the people in the loony bin are thinking, \"Well, at least I\'m an orange\"<br/><b>Jim Gaffigan</b>',
		'Slap-stick comedy is really funny, unless you\'re the one getting slapped with the stick<br/><b>Carroll Bryant</b>',
		'Sore loser? You bet your fuckin\' ass! What on earth is wrong with being a sore loser? It shows you cared about whatever the contest was in the first place. Fuck losing graciously--that\'s for chumps. And losers, by the way<br/><b>George Carlin</b>',
		'I had a dream about you last night...shortly after I woke up screaming in terror<br/><b>Amy Sommers</b>',
		'Fun war fact: there\'s are more crashed planes in the bottom of the ocean than there are crashed submarines in the sky<br/><b>Jeremy Dooley from \"On The Spot\"</b>',
		'Why does everyone have to pretend to be stupid and not know long words?<br/><b>Martin Freeman</b>',
		'If you were going to shoot a mime, would you use a silencer?<br/><b>Steven Wright</b>',
		'Whatever my ancestors did to you, none of them consulted me<br/><b>Tad Williams</b>',
		'Life is an endless series of trainwrecks with only brief, commercial-like breaks of happiness<br/><b>Deadpool</b>',
		'When it comes to being famous, you\'re usually the last to know, and the first to deny it. Unless you were already famous in your head. In which case, party on, Wayne! Party on, Garth!<br/><b>Carroll Bryant</b>',
		'What on earth would I do if four bears came into my camp? Why, I would die of course. Literally shit myself lifeless<br/><b>Bill Bryson</b>',
		'What\'s a wingding? Why a wingding is, uh...it\'s just like a shindig but without all the hullabaloo<br/><b>Cuthbert Soup</b>',
		'The brain can be a dangerous thing. Even more so if you haven\'t got one<br/><b>Dave Courtney</b>',
		'If a tie is like kissing your sister, losing is like kissing your grandmother with her teeth out<br/><b>George Brett</b>',
		'One of the fundamental rights of mankind should be that of wearing as many or as few clothes as one likes inside one\'s own home<br/><b>Sachin Kundalkar</b>',
		'I may not always be right, but when I am, I admit it<br/><b>Ken Murray</b>',
		'Have you guys ever thought about the fact that socks are like the donut holes of underpants?<br/><b>Travis McElroy</b>',
		'The problem is not the problem. The problem is your attitude towards the problem<br/><b>Captain Jack Sparrow from \"Pirates of the Caribbean\" series</b>',
		'One can hardly do anything productive when one knows there is cake in the fridge<br/><b>Joyce Rachelle</b>',
		'Often we have to remind our minds that the job of asshole is already taken<br/><b>Scott Stabile</b>',
		'I try very hard to be annoying! Don\'t insult my ability to annoy!<br/><b>Rick Riordan</b>',
		'Home is where, when you go there and tell people to get out, they have to leave<br/><b>Jim Butcher</b>',
		'We have normality. I repeat, we have normality. Anything you still can\'t cope with is therefore your own problem<br/><b>Douglas Adams</b>',
		'Of all the consumer products, chewing gum is perhaps the most ridiculous: it literally has no nourishment - you just chew it to give yourself something to do with your stupid idiot Western mouth. Half the world is starving, and the other\'s going, \"I don\'t actually need any nutrition, but it would be good to masticate, just to keep my mind off things\"<br/><b>Russell Brand</b>',
		'You can\'t make footprints in the sands of time if you\'re sitting on your butt. And who wants to make buttprints in the sands of time?<br/><b>Bob Moawad</b>',
		'A boy who once wiped his ass with poison ivy probably doesn\'t belong in a smart people\'s club<br/><b>Stephen King</b>',
		'Every intelligent being, whether it breathes or not, coughs nervously at some time in its life<br/><b>Terry Pratchett</b>',
		'So if animals aren\'t our friends, then what are they? The answer can be summed between two buns<br/><b>Stephen Colbert</b>',
		'I hate patience. Slows everything down<br/><b>J.D. Robb</b>',
		'Plans are invitation to disappointment<br/><b>Derek Landy</b>',
		'Anything that doesn\'t take years of your life and drive you to suicide hardly seems worth doing<br/><b>Cormac McCarthy</b>',
		'It\'s amazing that the amount of news that happens in the world every day always just exactly fits the newspaper<br/><b>Jerry Seinfield</b>',
		'I feel a disturbance. If\'s as if an infinite number of people are laughing and pitying me to the best of their abilities at once...and that many more are screaming at me to run very...VERY far away. As time passes, the voices become louder and louder and more urgent...and apparently more vulgar as well...HEY I HEARD THAT YOU ASSHOLE!<br/><b>Ghost Oogakari from \"Yet Again With a Little Extra Help\"</b>'
		
	];
	
	var usedQuotes = []; // empty array for used quotes
	
	document.getElementById('retrieve').onclick = function() {
		var indexToSplice = Math.floor(Math.random() * quotes.length);
		var spliceQuote = quotes.splice(indexToSplice, 1);
		usedQuotes.push(spliceQuote);
		print(spliceQuote);
		
		if (quotes.length == 0) {
			quotes = usedQuotes;
			usedQuotes = [];
		}
	};
	
	function print (q) {
		document.getElementById("send").innerHTML = q;
	}
})();
